name: flutterappexample
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: "^0.11.0"
  path_provider: ^1.6.5
  cupertino_icons: ^0.1.2
  english_words: ^3.1.5
  toast: ^0.1.5
  http: ^0.12.0+4
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  shared_preferences: ^0.5.7+3
  localstorage: ^3.0.1+4
  swipe_button: ^0.0.2
  font_awesome_flutter: ^8.5.0
  intl: ^0.15.8
  smooth_star_rating: ^1.0.3
#  rxJava
  rxdart: ^0.21.0
#  slider
  carousel_slider: ^1.3.0
  flutter_rating: ^0.0.2
#  tikotok
  avatar_glow: any
  getflutter: ^1.0.11
  flutter_money_formatter: ^0.8.2
  video_player: ^0.10.8+1
# Movies
  flutter_rating_bar: ^1.1.1
# Food
  carousel_pro: ^1.0.0
# flut_store
  line_icons: ^0.2.0
# ShowCard
  flutter_advanced_networkimage: 0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter


builders:
  json_widget: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/school/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/images/movie/
    - assets/images/menus/
    - assets/images/topmenu/
    - assets/images/popular_foods/
    - assets/images/bestfood/
    - assets/images/flut_store/
    - assets/images/bag/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
